---
title: "report"
format: html
editor: visual
author: Xinran Yang, Parth Tendulkar and Bagas Ari Wibawanto (Group: 404 Found)
---

## Executive Summary
The water insecurity data helps our team produce insightful maps of water resources and infrastructure nationwide in the US. These maps show socio-economic elements like housing and indoor plumbing that affect water use and needs. We integrate ACS data to help water resource managers and policymakers. This method would help identify vulnerable people and infrastructural needs.

## Introduction
Effective water management and policymaking need to understand the intricate relationship between socio-economic factors and water supplies. Annually updated, the U.S. Census Bureau's American Community Survey (ACS) provides demographic, social, economic, and housing data. In the next sections, we will explain how to use this data and offer water infrastructure and accessibility findings, such as showing how home infrastructure age, indoor plumbing prevalence, and household income affect water accessibility and affordability. This report will show how mapped ACS data can inform targeted actions and strategic planning for sustainable water resource management and infrastructure.

## Methodology

## Results

## Discussion, conclusion and recommendations

## Reference section
