name: R-Script-run

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev

      - name: Restore R packages with renv
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'

      - name: Install TinyTeX
        run: |
          Rscript -e 'install.packages("tinytex")'
          Rscript -e 'tinytex::install_tinytex()'

      - name: Add TinyTeX to PATH
        run: echo "$HOME/.TinyTeX/bin/x86_64-linux" >> $GITHUB_PATH

      - name: Install LaTeX packages
        run: tlmgr install koma-script

      - name: Install Quarto CLI
         run:|
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.313/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb

      - name: Render report.qmd to PDF
        run: quarto render report.qmd --to pdf
