name: R-CMD-check

on: [push, pull_request]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev

      - name: Restore R packages with renv
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'

      - name: Install TinyTeX for PDF rendering
        run: |
          Rscript -e 'install.packages("tinytex")'
          Rscript -e 'tinytex::install_tinytex()'

      - name: Install missing LaTeX packages
        run: |
          tlmgr install koma-script

      - name: Render Quarto document to PDF
        run: |
          quarto render report.qmd

  
