name: R-CMD-check

on: [push, pull_request]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            pandoc

      - name: Restore R packages with renv
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'

      - name: Install quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto document
        run: |
          quarto render report.qmd
